baseurl = "https://tfr-net.github.io/"
title = "TFR's Blog"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "TFR"
  info = "Cybersecurity enthusiast and developer."
  description = "TFR's personal website"
  keywords = "blog,developer,personal,cybersecurity,devops"
  avatarurl = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi.pinimg.com%2F736x%2F4f%2F0d%2Fd4%2F4f0dd4078675312a6ede8e5377f3b3b3.jpg&f=1&nofb=1&ipt=e2538032e146cf123b5e5b7b100e5ae2b66956dcf8e621fc7390416eb954c2ed"
  #gravatar = "john.doe@example.com"

  faviconSVG = "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ficon-library.com%2Fimages%2Fpenguin-icon%2Fpenguin-icon-19.jpg&f=1&nofb=1&ipt=25c01afccb1e5294ccff8c2e16c7568f95da4bf882b474e008d7ae7ef66219ac"

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x fa-fade"
  weight = 1
  url = "https://github.com/tfr-net/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x fa-fade"
  weight = 2
  url = "https://www.linkedin.com/in/cameron-paton-610a5324a/"
[[params.social]]
  name = "Steam"
  icon = "fa-brands fa-steam fa-2x fa-fade"
  weight = 3
  url = "https://steamcommunity.com/id/tfr-net"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about/"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url  = "projects/"